displayName=ToA Invocations
author=mxO-dev
description=Shows relevant invocations when entering ToA boss rooms
tags=toa,tombs,amascut,invocations,raid
plugins=com.toainvocations.ToaInvocationsPlugin
build=standard
